### PR TITLE
(TWILL-191), add eclipse settings to site

### PR DESCRIPTION
**Pull request by serranom**
Add .epf file and referenced it on the HowToContribute page

### CODE REVIEW

**Comment by chtyim** [comment]
Lgtm will merge it and update the site. Thanks

**Comment by hsaputra** [comment]
+1

**Comment by serranom** [comment]
Note, one thing about the eclipse prefs is that there seems to be no way to prevent insertion of an extra newline between import groups.  I just noticed that https://github.com/apache/twill/pull/29 has these inserted.  Are you guys all right with the diff noise?

**Comment by hsaputra** [comment]
I dont remember if the check style will barf about it. I dont use Eclipse, so could yo try if it pass them maven checkstyle?

**Comment by serranom** [comment]
The default mvn checkstyle for twill doesn't care about the newlines.  Just the order of things.  It is just that the IntelliJ prefs will probably remove the newlines when an IntelliJ user does a save on the file.

**Comment by hsaputra** [comment]
I personally dont' mind and actually prefer the extra blank new line =)

**Comment by hsaputra** [comment]
If no objection will merge this tomorrow

**Comment by hsaputra** [comment]
Oh sorry, Terence already commented about merging to the Site. Pls continue =P

**Comment by hsaputra** [comment]
Hi @serranom , I just noticed that the commits you made use different account than your pull request. I would advise to check it to make sure your contributions easily tracked in Github

**Comment by serranom** [comment]
oh... yeah, i've been using my personal github but committing from work.  do i need to do something for my PR for you now or is this just a good idea?

**Comment by chtyim** [comment]
I've merged the changes. Please close the PR (the asfgit only close PR with pushes that go to master branch).

**Comment by hsaputra** [comment]
Could you check your Git identity via `git config --global user.name` and `git config --global user.email` ?

**Comment by serranom** [comment]
i've now set up my twill git repo to have serranom and my github email.  so future commits will be correct.

**Comment by hsaputra** [comment]
Cool! Looking forward to  them =)

**Pull request closed without merging**
