### PR TITLE
(TWILL-207) Only use list of class names as the cache name

### PR DESCRIPTION
**Pull request by chtyim**
- Also some indentation changes (append `?w=1` in the URL of the file view will hide those whitespaces diff)

### CODE REVIEW

**Comment by anwar6953** [comment]
LGTM

**Comment by chtyim** [comment]
Force push a change to trigger travis build again.

**Comment by hsaputra** [comment]
This PR contains both style and functional change, could you help tell a bit where the important  changes happen?

**Comment by chtyim** [comment]
As said in the description, you will see the important changes when ignoring white space changes

**Comment by hsaputra** [comment]
Ah, yes, sorry, I thought I added the ignore white spaces when load the files changes view.

**Comment by hsaputra** [comment]
+1

**Pull request closed without merging**
